// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class BasicEntities1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasicEntities1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108262109364_BasicEntities1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
